# Dart/Flutter (pub) dependency parser.
#
#   pubspec.lock -> analyze_pubspec_lock
#
# pubspec.lock is YAML, generated by `dart pub get` / `flutter pub get`. Shape
# (indentation is significant and exact, 2 spaces per level):
#
#   packages:                        column-0, opens the block we care about
#     dio:                             2-space  <- package name key
#       dependency: "direct main"        4-space
#       description:                     4-space
#         name: dio                        6-space (nested map, ignored)
#         sha256: "…"                      6-space
#         url: "https://pub.dev"           6-space
#       source: hosted                   4-space  <- HOSTED packages only
#       version: "4.0.6"                  4-space  <- always double-quoted
#   sdks:                             column-0, closes the block
#     dart: ">=3.0.0 <4.0.0"
#     flutter: ">=3.10.0"
#
# Only `source: hosted` packages (pulled from pub.dev, or a self-hosted pub
# server) resolve to a checkable name+version pair. `source: git` (a VCS
# dependency pinned by commit, description holds url/ref/resolved-ref instead
# of name/sha256/url) and `source: path` (a local filesystem dependency) are
# both skipped the same way npm/ruby parsers skip link:/git-sourced deps — no
# pub.dev release to compare against advisories. `source: sdk` (the `flutter`
# and `dart` pseudo-packages the SDK itself provides) is skipped for the same
# reason. Because the emit only fires when source == "hosted" was seen, all
# three are excluded by construction; no explicit skip-list needed.
#
# The exactly-4-space checks (`^    source:` / `^    version:`) are what tell
# a package's OWN source/version apart from anything nested inside its
# 6-space "description:" sub-map: a 6-space line still starts with 4 spaces,
# but its 5th character is ALSO a space, so it fails to match the literal
# "source:"/"version:" that follows the 4-space prefix in the regex.
#
# The block ends at the next 2-space package key (flush + start a new one) or
# at the top-level "sdks:" key (flush + stop): both close the currently-open
# package the same way a `[[package]]` header change flushes Cargo.lock's
# TOML parser.
analyze_pubspec_lock() {
    local lockfile="$1"
    local eco="${2:-pub}"

    local vuln_count_before=${#VULNERABLE_PACKAGES[@]}

    local packages
    packages=$(awk '
    function emit_pkg() {
        if (pkg_name != "" && pkg_source == "hosted" && pkg_version != "") {
            print pkg_name "|" pkg_version
        }
        pkg_name = ""
        pkg_source = ""
        pkg_version = ""
    }
    BEGIN { in_packages = 0 }
    {
        gsub(/\r/, "", $0)                     # tolerate CRLF checkouts
    }
    # Top-level "packages:" key opens the block we scan.
    /^packages:[[:space:]]*$/ {
        in_packages = 1
        next
    }
    # Any OTHER column-0 (unindented) line — "sdks:" in practice, but treated
    # generically like every other YAML-block parser in this codebase — flushes
    # the pending package and closes the block for good.
    in_packages && /^[A-Za-z]/ {
        emit_pkg()
        in_packages = 0
        next
    }
    !in_packages { next }
    # 2-space package-name key: flush the previous package, start this one.
    /^  [A-Za-z0-9_]+:[[:space:]]*$/ {
        emit_pkg()
        line = $0
        sub(/^  /, "", line)
        sub(/:[[:space:]]*$/, "", line)
        pkg_name = line
        next
    }
    # 4-space "source: hosted" — git/path/sdk sources are simply never set,
    # so emit_pkg()s guard (pkg_source == "hosted") skips them by construction.
    /^    source:[[:space:]]*hosted[[:space:]]*$/ {
        pkg_source = "hosted"
        next
    }
    # 4-space "version: \"x.y.z\"" — always double-quoted in a real lockfile.
    /^    version:[[:space:]]*"/ {
        line = $0
        sub(/^    version:[[:space:]]*"/, "", line)
        sub(/".*$/, "", line)
        pkg_version = line
        next
    }
    END { emit_pkg() }
    ' "$lockfile" 2>/dev/null | sort -u)

    while IFS='|' read -r pkg_name version; do
        [ -z "$pkg_name" ] || [ -z "$version" ] && continue
        check_vulnerability "$eco" "$pkg_name" "$version" "$lockfile" || true
    done <<< "$packages"

    local vuln_count_after=${#VULNERABLE_PACKAGES[@]}
    if [ "$vuln_count_after" -eq "$vuln_count_before" ]; then
        echo -e "${GREEN}✓ [$lockfile] No vulnerabilities found${NC}"
    fi
}
