# Hex (Elixir/Erlang) dependency parser.
#
#   mix.lock -> analyze_mix_lock
#
# mix.lock is a literal Elixir map, generated by `mix deps.get`, ONE entry per
# line (Mix always emits it pre-sorted and pre-formatted this way; hand-edits
# are never expected to survive `mix deps.get` re-running). Shape:
#
#   %{
#     "jason": {:hex, :jason, "1.4.1", "<64-hex outer checksum>", [:mix], [{:decimal, "~> 1.0", [hex: :decimal, repo: "hexpm", optional: true]}], "hexpm", "<64-hex inner checksum>"},
#     "internal_auth": {:git, "https://github.com/example-org/internal_auth.git", "<40-hex commit sha>", []},
#   }
#
# Unlike every other lockfile in this codebase, this is NOT a block/indent
# structure to track — each dependency is already a complete, self-contained
# line, so a single per-line regex match is enough (no BEGIN/state-machine,
# no emit_pkg() flush-on-boundary dance).
#
# Only `{:hex, ...}` tuples (packages resolved from the hex.pm/private hex
# registry) are checkable. `{:git, ...}` tuples (and, per the same Mix
# resolver, `{:path, ...}` / `{:in_umbrella, ...}` — not modeled here since
# they never even reach a `{:hex,`-shaped line) pin a VCS ref or local sibling
# app instead, with no hex.pm release to compare against advisories — skipped
# the same way npm/ruby/dart parsers skip link:/git/path-sourced deps. Because
# the match anchor below REQUIRES the literal `{:hex,` immediately after the
# name key, git/path lines simply never match; no explicit skip-list needed.
#
# EXTRACTION: the quoted map key (the dependency's app name — what every real
# mix.lock uses, and what hex.pm PURLs/advisories key on too) is the FIRST
# quoted string on the line. The version is the FIRST quoted string AFTER the
# literal `{:hex,` tuple tag and its `:atom_name,` element — i.e. the 3rd
# tuple element, `"1.2.3"` in `{:hex, :name, "1.2.3", ...}`. The checksum
# fields, `[:mix]` build-tools list, and dependency sub-list are all ignored.
#
# NORMALIZATION: none. Hex package names are used as-is (same canon as
# npm/golang/cargo/gem/pub — see canon_purl_name() in src/31-parsers-purl.sh),
# matching hex.pm's own case-sensitive package naming.
analyze_mix_lock() {
    local lockfile="$1"
    local eco="${2:-hex}"

    local vuln_count_before=${#VULNERABLE_PACKAGES[@]}

    local packages
    packages=$(awk '
    # Anchor: a quoted map key followed by a literal `{:hex,` tuple tag.
    # `{:git, ...}` (and any other non-hex tuple) lines simply never match
    # this pattern, so they are excluded by construction.
    /^[[:space:]]*"[^"]+"[[:space:]]*:[[:space:]]*\{:hex,/ {
        line = $0

        # Package name: the first quoted string on the line (the map key).
        if (!match(line, /"[^"]+"/)) next
        name = substr(line, RSTART + 1, RLENGTH - 2)

        # Walk past "{:hex," then past the ":atom_name," element to reach
        # the tuple'\''s 3rd element, whose FIRST quoted string is the version.
        hexpos = index(line, "{:hex,")
        if (hexpos == 0) next
        rest = substr(line, hexpos + 6)
        commapos = index(rest, ",")
        if (commapos == 0) next
        rest = substr(rest, commapos + 1)
        if (!match(rest, /"[^"]+"/)) next
        ver = substr(rest, RSTART + 1, RLENGTH - 2)

        if (name != "" && ver != "") print name "|" ver
    }
    ' "$lockfile" 2>/dev/null | sort -u)

    while IFS='|' read -r pkg_name version; do
        [ -z "$pkg_name" ] || [ -z "$version" ] && continue
        check_vulnerability "$eco" "$pkg_name" "$version" "$lockfile" || true
    done <<< "$packages"

    local vuln_count_after=${#VULNERABLE_PACKAGES[@]}
    if [ "$vuln_count_after" -eq "$vuln_count_before" ]; then
        echo -e "${GREEN}✓ [$lockfile] No vulnerabilities found${NC}"
    fi
}
