source "https://rubygems.org"

gem "rack", "2.2.3"
gem "rake", "13.2.1"
gem "json", "2.7.2"
gem "nokogiri", "1.16.5"
gem "rspec-support", git: "https://github.com/rspec/rspec-support.git", tag: "v3.13.1"
gem "local_tool", path: "vendor/local_tool"
