parse_sarif_to_lookup_eval() {
    local raw_data="$1"

    # Use awk to parse SARIF JSON and extract vulnerabilities
    echo "$raw_data" | awk '
    function escape_sq(s) {
        gsub(/'\''/, "'\''\\'\'''\''", s)
        return s
    }

    BEGIN {
        pkg_count = 0
        in_results = 0
        in_result = 0
        depth = 0
        current_pkg = ""
        current_version = ""
    }

    {
        # Look for "results": [ array
        if ($0 ~ /"results"[[:space:]]*:[[:space:]]*\[/) {
            in_results = 1
            next
        }

        if (in_results) {
            # Track depth to find result objects
            if ($0 ~ /\{/) depth++
            if ($0 ~ /\}/) depth--

            # Extract package name from message text
            # Format: "text": "package-lock.json: next@16.0.4"
            if ($0 ~ /"text"[[:space:]]*:/) {
                text_line = $0
                sub(/.*"text"[[:space:]]*:[[:space:]]*"/, "", text_line)
                sub(/".*/, "", text_line)

                # Check if it contains package@version pattern
                if (text_line ~ /:[[:space:]]*[^:]+@[^[:space:]]+/) {
                    # Extract package@version after the colon
                    pkg_ver = text_line
                    sub(/.*:[[:space:]]*/, "", pkg_ver)

                    if (pkg_ver ~ /@/) {
                        split(pkg_ver, parts, "@")
                        if (parts[1] != "" && parts[2] != "") {
                            if (!(parts[1] in pkg_versions)) {
                                pkg_versions[parts[1]] = parts[2]
                                pkg_count++
                            } else {
                                if (pkg_versions[parts[1]] !~ parts[2]) {
                                    pkg_versions[parts[1]] = pkg_versions[parts[1]] "|" parts[2]
                                }
                            }
                        }
                    }
                }
            }

            if (depth == 0) in_results = 0
        }
    }

    END {
        # OPTIMIZED: Output package count FIRST (allows read without grep)
        printf "SARIF_PKG_COUNT=%d\n", pkg_count

        # SARIF carries no ecosystem info -> wildcard namespace "*:"
        # Output eval commands for exact versions
        for (pkg in pkg_versions) {
            nk = "*:" pkg
            printf "if [ -n \"${VULN_EXACT_LOOKUP['\''%s'\'']+x}\" ]; then VULN_EXACT_LOOKUP['\''%s'\'']+=\"|%s\"; else VULN_EXACT_LOOKUP['\''%s'\'']='\''%s'\''; fi\n", escape_sq(nk), escape_sq(nk), escape_sq(pkg_versions[pkg]), escape_sq(nk), escape_sq(pkg_versions[pkg])
        }
    }
    '
}

# Parse SBOM CycloneDX format to lookup tables
# SBOM format: Software Bill of Materials in CycloneDX JSON format
# Example: Generated by Trivy, Syft, etc.
parse_sbom_to_lookup_eval() {
    local raw_data="$1"

    # Use awk to parse SBOM JSON and extract vulnerabilities
    echo "$raw_data" | awk '
    function escape_sq(s) {
        gsub(/'\''/, "'\''\\'\'''\''", s)
        return s
    }

    # Canonicalize a package name for a given purl type (ecosystem).
    function canon_purl_name(eco, name,   lo, cnt, parts) {
        if (eco == "pypi") {
            lo = tolower(name)
            gsub(/[-_.]+/, "-", lo)
            return lo
        } else if (eco == "maven") {
            if (index(name, ":") > 0) return name
            cnt = split(name, parts, "/")
            if (cnt >= 2) return parts[cnt-1] ":" parts[cnt]
            return name
        } else if (eco == "composer" || eco == "githubactions" || eco == "nuget") {
            return tolower(name)
        } else if (eco == "swift") {
            lo = name
            sub(/^https?:\/\//, "", lo)
            sub(/\.git$/, "", lo)
            return tolower(lo)
        }
        return name
    }

    BEGIN {
        pkg_count = 0
        in_vulnerabilities = 0
        depth = 0
        current_pkg = ""
        current_version = ""
    }

    {
        # Look for "vulnerabilities": [ array
        if ($0 ~ /"vulnerabilities"[[:space:]]*:[[:space:]]*\[/) {
            in_vulnerabilities = 1
            next
        }

        if (in_vulnerabilities) {
            # Track depth
            if ($0 ~ /\{/) depth++
            if ($0 ~ /\}/) depth--

            # Look for affects array within vulnerability
            if ($0 ~ /"affects"[[:space:]]*:[[:space:]]*\[/) {
                in_affects = 1
            }

            if ($0 ~ /"ref"[[:space:]]*:/) {
                # Extract package ref: "pkg:npm/package@version"
                ref = $0
                sub(/.*"ref"[[:space:]]*:[[:space:]]*"/, "", ref)
                sub(/".*/, "", ref)

                # Only PURL refs carry package info (skip CycloneDX bom-ref UUIDs)
                if (ref ~ /^pkg:[^\/]+\//) {
                    # Split query string off first (it may contain "@")
                    sbom_main = ref
                    sbom_qp = index(ref, "?")
                    if (sbom_qp > 0) sbom_main = substr(ref, 1, sbom_qp - 1)

                    sbom_te = index(sbom_main, "/")
                    sbom_eco = substr(sbom_main, 5, sbom_te - 5)

                    # Split name/version at the LAST "@"
                    sbom_ap = 0
                    for (sbom_i = length(sbom_main); sbom_i > sbom_te; sbom_i--) {
                        if (substr(sbom_main, sbom_i, 1) == "@") { sbom_ap = sbom_i; break }
                    }
                    if (sbom_ap > sbom_te) {
                        sbom_path = substr(sbom_main, sbom_te + 1, sbom_ap - sbom_te - 1)
                        current_version = substr(sbom_main, sbom_ap + 1)
                        gsub(/%40/, "@", sbom_path)
                        gsub(/%2[fF]/, "/", sbom_path)
                        # Namespaced lookup key: "eco:name"
                        current_pkg = sbom_eco ":" canon_purl_name(sbom_eco, sbom_path)
                    }
                }

                if (current_pkg != "" && current_version != "") {
                    if (!(current_pkg in pkg_versions)) {
                        pkg_versions[current_pkg] = current_version
                        pkg_count++
                    } else {
                        if (pkg_versions[current_pkg] !~ current_version) {
                            pkg_versions[current_pkg] = pkg_versions[current_pkg] "|" current_version
                        }
                    }
                    current_pkg = ""
                    current_version = ""
                }
            }

            if (depth == 0) in_vulnerabilities = 0
        }
    }

    END {
        # OPTIMIZED: Output package count FIRST (allows read without grep)
        printf "SBOM_PKG_COUNT=%d\n", pkg_count

        # Output eval commands for exact versions
        for (pkg in pkg_versions) {
            printf "if [ -n \"${VULN_EXACT_LOOKUP['\''%s'\'']+x}\" ]; then VULN_EXACT_LOOKUP['\''%s'\'']+=\"|%s\"; else VULN_EXACT_LOOKUP['\''%s'\'']='\''%s'\''; fi\n", escape_sq(pkg), escape_sq(pkg), escape_sq(pkg_versions[pkg]), escape_sq(pkg), escape_sq(pkg_versions[pkg])
        }
    }
    '
}

# Parse Trivy JSON format to lookup tables
# Trivy format: Trivy JSON output from filesystem or container scans
# Example: trivy fs --format json --output trivy-report.json .
parse_trivy_to_lookup_eval() {
    local raw_data="$1"

    # Use awk to parse Trivy JSON and extract vulnerabilities
    echo "$raw_data" | awk '
    function escape_sq(s) {
        gsub(/'\''/, "'\''\\'\'''\''", s)
        return s
    }

    # Canonicalize a package name for a given purl type (ecosystem).
    function canon_purl_name(eco, name,   lo, cnt, parts) {
        if (eco == "pypi") {
            lo = tolower(name)
            gsub(/[-_.]+/, "-", lo)
            return lo
        } else if (eco == "maven") {
            if (index(name, ":") > 0) return name
            cnt = split(name, parts, "/")
            if (cnt >= 2) return parts[cnt-1] ":" parts[cnt]
            return name
        } else if (eco == "composer" || eco == "githubactions" || eco == "nuget") {
            return tolower(name)
        } else if (eco == "swift") {
            lo = name
            sub(/^https?:\/\//, "", lo)
            sub(/\.git$/, "", lo)
            return tolower(lo)
        }
        return name
    }

    # Build a namespaced key ("eco:name") from a purl string, or "" if not a purl
    function purl_to_key(purl,   pmain, pqp, pte, peco, pap, pi, ppath) {
        if (purl !~ /^pkg:[^\/]+\//) return ""
        pmain = purl
        pqp = index(purl, "?")
        if (pqp > 0) pmain = substr(purl, 1, pqp - 1)
        pte = index(pmain, "/")
        peco = substr(pmain, 5, pte - 5)
        pap = 0
        for (pi = length(pmain); pi > pte; pi--) {
            if (substr(pmain, pi, 1) == "@") { pap = pi; break }
        }
        if (pap <= pte) return ""
        ppath = substr(pmain, pte + 1, pap - pte - 1)
        gsub(/%40/, "@", ppath)
        gsub(/%2[fF]/, "/", ppath)
        return peco ":" canon_purl_name(peco, ppath)
    }

    BEGIN {
        pkg_count = 0
        in_results = 0
        in_vulnerabilities = 0
        depth = 0
        current_pkg = ""
        current_version = ""
        current_purl_key = ""
    }

    {
        # Look for "Results": [ array
        if ($0 ~ /"Results"[[:space:]]*:[[:space:]]*\[/) {
            in_results = 1
            next
        }

        if (in_results) {
            # Track depth
            if ($0 ~ /\{/) depth++
            if ($0 ~ /\}/) depth--

            # Look for "Vulnerabilities": [ array within Results
            if ($0 ~ /"Vulnerabilities"[[:space:]]*:[[:space:]]*\[/) {
                in_vulnerabilities = 1
            }

            if (in_vulnerabilities) {
                # Extract PkgName
                if ($0 ~ /"PkgName"[[:space:]]*:/) {
                    pkg = $0
                    sub(/.*"PkgName"[[:space:]]*:[[:space:]]*"/, "", pkg)
                    sub(/".*/, "", pkg)
                    if (pkg != "") current_pkg = pkg
                }

                # Extract PkgIdentifier.PURL (preferred: carries ecosystem)
                if ($0 ~ /"PURL"[[:space:]]*:/) {
                    purl = $0
                    sub(/.*"PURL"[[:space:]]*:[[:space:]]*"/, "", purl)
                    sub(/".*/, "", purl)
                    if (purl != "") current_purl_key = purl_to_key(purl)
                }

                # Extract InstalledVersion
                if ($0 ~ /"InstalledVersion"[[:space:]]*:/) {
                    ver = $0
                    sub(/.*"InstalledVersion"[[:space:]]*:[[:space:]]*"/, "", ver)
                    sub(/".*/, "", ver)
                    if (ver != "") current_version = ver
                }

                # When we close a vulnerability object and have both pkg and version
                if ($0 ~ /\}/ && current_pkg != "" && current_version != "") {
                    # Use the PURL-derived namespaced key when available; otherwise
                    # this result has no ecosystem info -> wildcard namespace "*:"
                    if (current_purl_key != "") {
                        store_key = current_purl_key
                    } else {
                        store_key = "*:" current_pkg
                    }
                    if (!(store_key in pkg_versions)) {
                        pkg_versions[store_key] = current_version
                        pkg_count++
                    } else {
                        if (pkg_versions[store_key] !~ current_version) {
                            pkg_versions[store_key] = pkg_versions[store_key] "|" current_version
                        }
                    }
                    current_pkg = ""
                    current_version = ""
                    current_purl_key = ""
                }
            }

            if (depth == 0) {
                in_results = 0
                in_vulnerabilities = 0
            }
        }
    }

    END {
        # OPTIMIZED: Output package count FIRST (allows read without grep)
        printf "TRIVY_PKG_COUNT=%d\n", pkg_count

        # Output eval commands for exact versions
        for (pkg in pkg_versions) {
            printf "if [ -n \"${VULN_EXACT_LOOKUP['\''%s'\'']+x}\" ]; then VULN_EXACT_LOOKUP['\''%s'\'']+=\"|%s\"; else VULN_EXACT_LOOKUP['\''%s'\'']='\''%s'\''; fi\n", escape_sq(pkg), escape_sq(pkg), escape_sq(pkg_versions[pkg]), escape_sq(pkg), escape_sq(pkg_versions[pkg])
        }
    }
    '
}

# Detect format from URL
